// Generated by CoffeeScript 1.7.1
(function() {
  var Validation;

  Validation = (function() {
    function Validation(props) {
      if (props == null) {
        props = {};
      }
      this.subject = props.subject;
      this.errors = props.errors;
    }

    Validation.prototype.addError = function(key, message) {
      if (this.errors == null) {
        this.errors = {};
      }
      if (this.errors[key] == null) {
        this.errors[key] = [];
      }
      return this.errors[key].push(message);
    };

    Validation.prototype.isInvalid = function() {
      return (this.errors != null) && Object.getOwnPropertyNames(this.errors).length > 0;
    };

    Validation.prototype.isValid = function() {
      return !this.isInvalid();
    };

    return Validation;

  })();

  module.exports = Validation;

}).call(this);

//# sourceMappingURL=Validation.map
